# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anton Prokopovich
title: Software Engineer
email: 96anton96@mail.ru

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  "antonprokopovich"
linkedin_username: "anton-prokopovich-500744141"
facebook_username: "anton.prokopovich.3"

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-NBZVP671HE"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer with experience in robotics, backend, and infrastructure development.
  
  Technologies and skills that I have the most experience with: <mark>Golang</mark>, <mark>Python</mark>, Python data science stack [ <mark>sci-kit learn</mark>, <mark>scipy</mark>, <mark>numpy</mark>, <mark>matplotlib</mark>, <mark>pandas</mark> ], <mark>gRPC</mark>, <mark>PostgreSQL</mark>, <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>Kubernetes</mark>, <mark>Kafka</mark>, <mark>RabbitMQ</mark>, <mark>ZeroMQ</mark>,  <mark>Linux</mark>,  <mark>ROS Framework</mark>, <mark>OpenTelemetry</mark>, <mark>Gitlab CI</mark>, <mark>Software Architecture</mark>, <mark>TDD</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sber.Infra
        link: www.sberbank.com
        link_text: sberbank.com
        sub_title: |
          Lead Software Engineer
          (Golang)
        caption: 2022 - Present
        description: | # this will include new lines to allow paragraphs
          #### Key projects 
          
          <ins>Managed ML Inference Platform</ins>
        
            The platform provides functionality to simplify and optimize the following stages of working with Machine Learning models:
            - Preparing and allocating the resources (GPU/CPU/RAM) and infrastructure for running ML models.
            - Deploying and scaling models in distributed Kubernetes clusters.
            - Building model ensembles.
            - Running inference on deployed models.
            - Collecting and displaying metrics, logs and traces of deployed models.
          
          <ins>Managed Kubernetes Platform</ins>
          
            The Managed Kubernetes platform is used by majority of development teams at Sber - the largest bank in Russia.
            The platform consists of multitude of microservices. The majority of those microservices are various k8s-controllers, backends and componets that implement integrations with other services of the Cloud platform.
          
          <ins>Managed Namespaces</ins>
          
            A platform that allows users to manage namespaces in kubernetes clusters. The managed namespaces are also used to implement the communal (shared) kubernetes clusters which helps to better utilize clusters' compute resources. 
          
          #### Additional roles
          
            I'm leading a team of 4 software engineers. So besides the development work I'm also responsible for translating business goals and requirements into technical tasks, assigning those tasks to the team members, doing code reviews and testing, preparing releases, taking part in designing systems architecture and removing blockers for the team.
            
            I'm also responsible for interviewing Golang developers in multiple teams and departments. 
                      
            Other than that, I'm a member of the Sber Golang Experts Team (~20 people). The team is responsible for actively improving and developing Golang-related tools and processes in the company.

      - layout: left
        title: Bitsgap
        link: www.bitsgap.com
        link_text: bitsgap.com
        sub_title: "Software Engineer\n(Golang)"
        caption: 2022
        description: | # this will include new lines to allow paragraphs
          #### Key projects
          
          <ins>DCA Trading Bot Backend</ins>
          
          During my time at Bitsgap I worked on a cryptocurrency trading bot that implemented DCA trading strategy.
          
          Besides implementing new features and improving performance, I also refactored the backend architecture and
          introduced the automated testing practices to the project.
      - layout: left
        title: Zyfra Robotics
        link: www.zyfra.com/industries/robotics
        link_text: zyfra.com
        sub_title: "Software Engineer\n(Python, Robotics)"
        caption: 2018 - 2022
        description: | # this will include new lines to allow paragraphs
          
          #### Key projects
          
          At Zyfra Robotics I worked on automating vehicles (trucks, drilling rigs) in the mining industry. Despite it being my first software engineering job I ended up as the main developer on the following projects because I was the only developer on a team of two – just me and my team lead/architect.           
          
          <ins>Drilling Rig Robot Controll Software</ins>
          
          I was responsible for the development of the software that controlled the [drilling rig robots](https://www.youtube.com/watch?v=B3JCit_YW5U&ab_channel=ZyfraCompany) and the infrastructure that supported them. The controll software development involved a lot mathematics (geometry, probability, linear argebra) and control theory (PID regulators, Path-Finding Algorithms, Kalman Filters).
        
          <ins>Planning and Observability Backend</ins>
        
          Besides the controll software I developed the backend that communicated with all robotic vehicles on the mine, gathered telemetry from them, sent them tasks. The backend also provided REST API for sending plans of tasks to robots (through a Web interface) and observing their current state.
        
          <ins>Remote Controll Station Desktop App</ins>
        
          I also developed a desktop app that allowed the drilling rigs to be controlled remotely using the remote-controll station built by our engineers.
        
          <ins>3D Simulator</ins>
        
          I worked on a 3D-simulator of the drilling rig which we later used for testing the main system.
        
          The automonous drilling rig was deployed on mines in Russia and Peru.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Presbyterian College 
        caption: 2016 - 2016 (Global UGRAD Program Scholarship)
        sub_title: BSc Business Administration
        description: | # this will include new lines to allow paragraphs
          I became a finalist of the [Global UGRAD](https://exchanges.state.gov/non-us/program/global-undergraduate-exchange-program-global-ugrad) scholarship program and went to study to the [Presbyterian College](https://en.wikipedia.org/wiki/Presbyterian_College) for a semester.
          
          I [scored 97](images/TOEFL_iBT.pdf) on my TOEFL exam which was a part of the Global UGRAD scholarship selection process.
          
          In addition to my business major curriculum at Presbyterian College, I took logic courses as electives.

      - layout: left
        title: Russian State University for the Humanities
        caption: 2014 - 2018
        sub_title: BSc Human Resources Management
        description: | # this will include new lines to allow paragraphs
          I received a [bachelor's degree](images/bachelors_degree.jpeg) in Human Resources Management from [RSUH](https://en.wikipedia.org/wiki/Russian_State_University_for_the_Humanities). After the second year I started spending all my spare time studying [machine learning](images/mipt_yandex_ml_supervised.pdf), [mathematics and programming](images/mipt_yandex_math.pdf). 

  - title: Personal projects # Title for the section
    sub_title: Some of the pet-projects I've worked on in my spare time.
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Threads.net API wrapper in Golang
        link: github.com/antonprokopovich/go-threads
        # link_text: Project Website
        additional_links:
          - title: antonprokopovich/go-threads
            icon: fab fa-github
            url: github.com/antonprokopovich/go-threads
        description: | # this will include new lines to allow paragraphs
          I've reverse-engineered API for Threads.net the first days it came out and created a Golang wrapper for it.
      - layout: left
        title: Two-Layer Feedforward Neural Network
        link: github.com/antonprokopovich/NeuralNet
        # link_text: Project Website
        additional_links:
          - title: antonprokopovich/NeuralNet
            icon: fab fa-github
            url: github.com/antonprokopovich/NeuralNet
        description: | # this will include new lines to allow paragraphs
          Two-layer feed-forward neural network that solves a classic problem of handwritten digits classification. Implemented from scratch in pure Python (numpy being the only third-party dependency).

  - title: Open source contributions
    layout: text
    content: |
      I've made a few _minor_ contributions to some projects in the open-source community:
      - Found [an issue](https://github.com/metal-stack/go-ipam/issues/112) in a Golang IP-management library and [added a unit test](https://github.com/metal-stack/go-ipam/pull/113/files) to reproduce it.
      - Found [an issue](https://github.com/jackc/pgx/issues/1470) with type casting in the Golang Postgres driver library pgx/v5 which was [reproduced and fixed](https://github.com/jackc/pgx/commit/e48e7a7189354fd7d2990b8abc2c40dfe5ee4c9f) by the library author. 

  - title: Honors & Recognitions
    sub_title: Some of the commendation certificates I received in recognition of my work.
    layout: text
    content: |
      **Commendation from Sber Tech Department**
      
      I received the commendation from the department for high performance and major contributations at work throughout the year 2024
      
      Year: 2024
      
      <img src="/images/2024_high_performance.jpeg" width="285" height="394">
      
      **Commendation from programming school ["School 21"](https://21-school.ru/)**
      
      I received the commendation for high quality conduction of Golang interviews for the school graduates
      
      Year: 2024
      
      <img src="/images/school_21_go.png" width="285" height="394">
      
      **Global UGRAD Scholarship**
      
      I became a finalist of the [Global UGRAD](https://exchanges.state.gov/non-us/program/global-undergraduate-exchange-program-global-ugrad) scholarship program and went to study to the [Presbyterian College](https://en.wikipedia.org/wiki/Presbyterian_College).
      
      Year: 2016
      
      <img src="/images/usa_embassy_letter.png" width="285" height="380" style="border: 1px solid grey;">

  - title: Other
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides software engineering and computer science some of my other interests are:
      - Machine Learning and AI.
      - Neuroscience. I enjoy learning about how human brain functions at a fundamental level.
      - Reading. In my spare time I read both technical and fiction literature. Planning to add my reading list on here.
      - Health and Fitness. I played basketball for 10 years in my youth and was a member of Russian U16 National Team. I enjoy weightlifting and learning/practicing anything related to becoming stronger and healthier.

# Footer
#footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
