# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anton Prokopovich
title: Senior Software Engineer
email: 96anton96@mail.ru
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  "antonprokopovich"
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: "anton.prokopovich.3"
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: "anton-prokopovich-500744141"
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm a software engineer with experience in robotics, backend, and infrastructure development.

#  Key skills: <mark>Golang</mark>, <mark>Python</mark>, <mark>Kubernetes</mark>, <mark>Software Architecture</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sber
        link: www.sberbank.com
        link_text: sberbank.com
        sub_title: |
          Lead Software Engineer
          (Golang)
        caption: 2022 - Present
        description: | # this will include new lines to allow paragraphs
          We're developing a Managed Kubernetes platform used by all development teams at Sber - the largest bank in Russia (~300,000 employees as of 2024).
          I'm also responsible for interviewing and mentoring new team members, as well as leading a sub-team of 3 software engineers.
          
          I'm also a member of the Sber Golang Experts Team (~20 people).
      - layout: left
        title: Bitsgap
        link: www.bitsgap.com
        link_text: bitsgap.com
        sub_title: "Software Engineer\n(Golang)"
        caption: 2022 - 2022
        description: | # this will include new lines to allow paragraphs
          During my time at Bitsgap I worked on cryptocurrency trading bot that implemented DCA trading strategy.
          
          Besides implementing new features and improving performance, I also refactored the backend architecture and
          imptroduced the automated testing practices to the project.
      - layout: left
        title: Zyfra Robotics
        link: www.zyfra.com/industries/robotics
        link_text: zyfra.com
        sub_title: "Software Engineer\n(Python, Robotics)"
        caption: 2019 - 2022
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            There I worked on automating vehicles (trucks, drilling rigs) in mining industry. 
          
            I was responsible for the development of the software that controlled the (drilling rig robots)[https://www.youtube.com/watch?v=KnGj2X02N1Q&ab_channel=Zyfra] and the infrastructure that supported them.
            I also developed a system that allowed the drilling rigs to be controlled remotely from a graphical interface. And also worked on 3D similator of the drilling rig which we later used for testing the main system.
          
            The automonous drilling rig was deployed on mines in Russia and Peru.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Presbyterian College 
        caption: 2016 - 2016 (Global UGRAD Program Scholarship)
        sub_title: BSc Business Administration
#        quote: >
#          I became a winner of a Global UGRAD scholarship program and went to study to the Presbyterian College for a semester.
        description: | # this will include new lines to allow paragraphs
          I became a finalist of the Global UGRAD scholarship program and went to study to the Presbyterian College for a semester.
          
          I scored 97 on my TOEFL exam, which was a part of the Global UGRAD scholarship selection process.
          
          In addition to my business major curriculum at Presbyterian College, I took logic and mathematics courses as electives.

      - layout: left
        title: Russian State University for the Humanities
        caption: 2014 - 2018
        sub_title: BSc Human Resources Mangement
#        quote: >
#          Got a bachelor's degree in Human Resources Management. After second year I started spending all my spare time studying mathematics and programming. Fun fact: my thesis title was "Use of Information Technologies in the Recruitment Process: A Case Study of Sberbank" and 5 years later I work as a software engineer in Sberbank Tech department and participate in recruiting new people to our team :).
        description: | # this will include new lines to allow paragraphs
          I recieved a bachelor's degree in Human Resources Management. After the second year I started spending all my spare time studying mathematics and programming. 
          
          Fun fact: my thesis title was "Use of Information Technologies in the Recruitment Process: A Case Study of Sberbank" and 5 years later I work in Sberbank Tech department and am responsible for recruiting new developers to our team :)

  - title: Personal projects # Title for the section
    sub_title: Few of the pet-projects I've worked on in my spare time.
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Threads.net API wrapper in Golang
        link: github.com/antonprokopovich/go-threads
        # link_text: Project Website
        additional_links:
          - title: antonprokopovich/go-threads
            icon: fab fa-github
            url: github.com/antonprokopovich/go-threads
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #        quote: >
        #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I've reversed engineered API for Threads.net the first days it came out and created a Golang wrapper for it.

  - title: Other
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides software engineering and computer science some of my other interests are:
      - Machine Learning and AI.
      - Neuroscience. I enjoy learning about how human brain functions at a fundamental level.
      - Reading. I read a lot of both technical and fiction literature. Planning to add my reading list on here, stay tuned :)
      - Health and Fitness. I played basketball for 10 years in my youth. I enjoy weightlifting and learning/practicing anything related to becoming stronger and healthiers.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
